name: Create pull request templates

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 0

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request-templates:
    if: ${{ github.repository == 'alextheman231/alex-c-line' }}
    uses: alextheman231/github-actions/.github/workflows/create-pull-request-templates.yml@894b5b5d4d00aa34612d102b7a7721fd7bc4fc3b # v7.2.4
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
