name: Create pull request templates

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 0

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request-templates:
    if: ${{ github.repository == 'alextheman231/alex-c-line' }}
    uses: alextheman231/github-actions/.github/workflows/create-pull-request-templates.yml@dc7b936f77246a5f69108b4ecd2f1c20eb57188b # v7.2.3
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
