name: Publish the package

on:
  push:
    branches:
      - main

jobs:
  npm-registry-publish:
    permissions:
      id-token: write
    if: ${{ github.repository == 'AlexMan123456/alex-c-line' }}
    uses: AlexMan123456/github-actions/.github/workflows/npm-registry-publish.yml@78be199abfba7efedbc8a151b98a58963038cad7 # v4.0.4
  
  create-github-release:
    needs: npm-registry-publish
    permissions:
      contents: write
    if: ${{ github.repository == 'AlexMan123456/alex-c-line' }}
    uses: AlexMan123456/github-actions/.github/workflows/create-github-release.yml@78be199abfba7efedbc8a151b98a58963038cad7 # v4.0.4
    secrets:
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
