name: Publish the package

on:
  push:
    branches:
      - main

jobs:
  npm-registry-publish:
    permissions:
      id-token: write
    if: ${{ github.repository == 'alextheman231/alex-c-line' }}
    uses: alextheman231/github-actions/.github/workflows/npm-registry-publish.yml@e549458ca0a641e030d97cf7817f8b619b1ebb18 # v7.2.5

  create-github-release:
    needs: npm-registry-publish
    permissions:
      contents: write
    if: needs.npm-registry-publish.outputs.did_publish == 'true'
    uses: alextheman231/github-actions/.github/workflows/create-github-release.yml@e549458ca0a641e030d97cf7817f8b619b1ebb18 # v7.2.5
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
