name: Publish the package

on:
  push:
    branches:
      - main

jobs:
  npm-registry-publish:
    permissions:
      id-token: write
    if: ${{ github.repository == 'alextheman231/alex-c-line' }}
    uses: alextheman231/github-actions/.github/workflows/npm-registry-publish.yml@40d4eac5a7058957e6fe46cafe068d92eade73d8 # v7.0.1

  create-github-release:
    needs: npm-registry-publish
    permissions:
      contents: write
    if: needs.npm-registry-publish.outputs.did_publish == 'true'
    uses: alextheman231/github-actions/.github/workflows/create-github-release.yml@40d4eac5a7058957e6fe46cafe068d92eade73d8 # v7.0.1
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
